services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  caddy:
    image: caddy:latest
    container_name: caddy_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./www:/var/www/html
    depends_on:
      - mysql

  php:
    build: ./php
    container_name: php_container
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql

  adminer:
    image: adminer
    container_name: adminer_container
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DEFAULT_DB: db
      ADMINER_DEFAULT_USER: user
      ADMINER_DEFAULT_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
  caddy_data:
  caddy_config:
